# tmux configuration file
#
# Copyright 2026 Buo-ren Lin <buo.ren.lin@gmail.com>
# SPDX-License-identifier: CC-BY-SA 4.0+

# Pass terminal emulator's focus events to software running in tmux
set -g focus-events on
